[project]
authors = ["Hernan Picatto <hernan.picatto@ascii.ac.at>"]

channels = [
  { channel = "rapidsai", priority = 3 },
  { channel = "conda-forge", priority = 2 },
  { channel = "pytorch", priority = 1 },
  {channel = "conda-forge", priority = 1},
]
name = "IntroSC"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "~=3.13"
pip = ">=24.2"
nodejs = ">=20.8.1,<23"

[environments]
lint = { features = [
  "research-intro-sc",
  "typings",
], solve-group = "default" }
research-intro-sc = { features = [
  "research-intro-sc",
  "research-basics",
], solve-group = "default" }

[feature.typings.pypi-dependencies]
pytest = ">=8.3.3,<9"
pytest-mock = ">=3.14.0,<4"
pytest-cov = ">=5.0.0,<6"
ruff = ">=0.5.7,<1"
yamllint = ">=1.35.1,<2"
taplo = ">=0.9.3,<0.10"
nbqa = "~=1.9.0"
pyright = "~=1.1.388"

[feature.research-intro-sc.dependencies]
[feature.research-intro-sc.pypi-dependencies]
pybind11= "~=2.13"
sphinx-rtd-theme= "~=3.0"
jupyter= "~=1.1"
numpy= "~=2.2"
scipy= "~=1.15"
matplotlib= "~=3.10"
ngsolve= "~=6.2"

[feature.research-basics.dependencies]

[tasks]
create_environment = { cmd = "pixi install -e research-intro-sc --locked && pixi run -e research-intro-sc postinstall", description = "research intro-sc environment" }
clean_all_environments = { cmd = "rm -rf .pixi/envs" }
notebook_intro_sc = { cmd = "pixi run -e research-intro-sc --frozen jupyter lab" }

[tasks.clean_notebooks]
cmd = ["sh", "../../scripts/clean_notebooks.sh"]
cwd = "./src/notebooks"
description = "Clear outputs from all Jupyter notebooks in the research folder"

[tasks.fmt_unsafe]
cmd = "nbqa 'ruff format' src/* && ruff format ./src && nbqa ruff --fix --unsafe-fixes ./src/* && ruff check --fix --unsafe-fixes ./src/ && yamllint -c yamllintconfig.yaml . && taplo fmt"
description = "Format python files - apply automatic ruff unsafe fixes"

[tasks.lint]
cmd = "ruff check ./src/pipelines && yamllint -c yamllintconfig.yaml . && taplo check && pyright"
description = "Validate formatting and type check python files"
